<?xml_version="1.0" encoding="utf-8"?>
<ArrayOfEntry xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Entry>
        <Name>timeStamp</Name>
        <Xpath>/SPAT/timeStamp</Xpath>
        <OutputBehavior>Number</OutputBehavior>
        <MaxLength></MaxLength>
        <Invalid>-1</Invalid>
    </Entry>
    <Entry>
        <Name>num_Intersections</Name>
        <Xpath>/SPAT/intersections</Xpath>
        <OutputBehavior>Count</OutputBehavior>
        <MaxLength></MaxLength>
        <Invalid></Invalid>
    </Entry>
    <Entry>
        <Name>intersectionID_SPaT</Name>
        <Xpath>/SPAT/intersections/IntersectionState[1]/id/id</Xpath>
        <OutputBehavior>Number</OutputBehavior>
        <MaxLength></MaxLength>
        <Invalid>-1</Invalid>
    </Entry>
    <Entry>
        <Name>Intersection_1_num_States</Name>
        <Xpath>/SPAT/intersections/IntersectionState[1]/states</Xpath>
        <OutputBehavior>Count</OutputBehavior>
        <MaxLength></MaxLength>
        <Invalid></Invalid>
    </Entry>
    <!-- Movement State 1 -->
    <Entry>
        <Name>Intersection_1_MovementState_1_signalGroup</Name>
        <Xpath>/SPAT/intersections/IntersectionState[1]/states/MovementState[1]/signalGroup</Xpath>
        <OutputBehavior>Number</OutputBehavior>
        <MaxLength></MaxLength>
        <Invalid>-1</Invalid>
    </Entry>
    <Entry>
        <Name>Intersection_1_MovementState_1_has_MovementEvent</Name>
        <Xpath>/SPAT/intersections/IntersectionState[1]/states/MovementState[1]/state-time-speed/MovementEvent</Xpath>
        <OutputBehavior>Exists</OutputBehavior>
        <MaxLength></MaxLength>
        <Invalid></Invalid>
    </Entry>
    <Entry>
        <Name>Intersection_1_MovementState_1_MovementEvent_eventState</Name>
        <Xpath>/SPAT/intersections/IntersectionState[1]/states/MovementState[1]/state-time-speed/MovementEvent/eventState</Xpath>
        <OutputBehavior>String</OutputBehavior>
        <MaxLength>27</MaxLength>
        <Invalid></Invalid>
    </Entry>
    <Entry>
        <Name>Intersection_1_MovementState_1_MovementEvent_startTime</Name>
        <Xpath>/SPAT/intersections/IntersectionState[1]/states/MovementState[1]/state-time-speed/MovementEvent/timing/startTime</Xpath>
        <OutputBehavior>Number</OutputBehavior>
        <MaxLength></MaxLength>
        <Invalid>-1</Invalid>
    </Entry>
    <Entry>
        <Name>Intersection_1_MovementState_1_MovementEvent_minEndTime</Name>
        <Xpath>/SPAT/intersections/IntersectionState[1]/states/MovementState[1]/state-time-speed/MovementEvent/timing/minEndTime</Xpath>
        <OutputBehavior>Number</OutputBehavior>
        <MaxLength></MaxLength>
        <Invalid>-1</Invalid>
    </Entry>
    <Entry>
        <Name>Intersection_1_MovementState_1_MovementEvent_likelyTime</Name>
        <Xpath>/SPAT/intersections/IntersectionState[1]/states/MovementState[1]/state-time-speed/MovementEvent/timing/likelyTime</Xpath>
        <OutputBehavior>Number</OutputBehavior>
        <MaxLength></MaxLength>
        <Invalid>-1</Invalid>
    </Entry>
    <Entry>
        <Name>Intersection_1_MovementState_1_MovementEvent_maxEndTime</Name>
        <Xpath>/SPAT/intersections/IntersectionState[1]/states/MovementState[1]/state-time-speed/MovementEvent/timing/maxEndTime</Xpath>
        <OutputBehavior>Number</OutputBehavior>
        <MaxLength></MaxLength>
        <Invalid>-1</Invalid>
    </Entry>
    <Entry>
        <Name>Intersection_1_MovementState_1_MovementEvent_confidence</Name>
        <Xpath>/SPAT/intersections/IntersectionState[1]/states/MovementState[1]/state-time-speed/MovementEvent/timing/confidence</Xpath>
        <OutputBehavior>Number</OutputBehavior>
        <MaxLength></MaxLength>
        <Invalid>-1</Invalid>
    </Entry>
    <Entry>
        <Name>Intersection_1_MovementState_1_MovementEvent_nextTime</Name>
        <Xpath>/SPAT/intersections/IntersectionState[1]/states/MovementState[1]/state-time-speed/MovementEvent/timing/nextTime</Xpath>
        <OutputBehavior>Number</OutputBehavior>
        <MaxLength></MaxLength>
        <Invalid>-1</Invalid>
    </Entry>
    <!-- Movement State 2 -->
    <Entry>
        <Name>Intersection_1_MovementState_2_signalGroup</Name>
        <Xpath>/SPAT/intersections/IntersectionState[1]/states/MovementState[2]/signalGroup</Xpath>
        <OutputBehavior>Number</OutputBehavior>
        <MaxLength></MaxLength>
        <Invalid>-1</Invalid>
    </Entry>
    <Entry>
        <Name>Intersection_1_MovementState_2_has_MovementEvent</Name>
        <Xpath>/SPAT/intersections/IntersectionState[1]/states/MovementState[2]/state-time-speed/MovementEvent</Xpath>
        <OutputBehavior>Exists</OutputBehavior>
        <MaxLength></MaxLength>
        <Invalid></Invalid>
    </Entry>
    <Entry>
        <Name>Intersection_1_MovementState_2_MovementEvent_eventState</Name>
        <Xpath>/SPAT/intersections/IntersectionState[1]/states/MovementState[2]/state-time-speed/MovementEvent/eventState</Xpath>
        <OutputBehavior>String</OutputBehavior>
        <MaxLength>27</MaxLength>
        <Invalid></Invalid>
    </Entry>
    <Entry>
        <Name>Intersection_1_MovementState_2_MovementEvent_startTime</Name>
        <Xpath>/SPAT/intersections/IntersectionState[1]/states/MovementState[2]/state-time-speed/MovementEvent/timing/startTime</Xpath>
        <OutputBehavior>Number</OutputBehavior>
        <MaxLength></MaxLength>
        <Invalid>-1</Invalid>
    </Entry>
    <Entry>
        <Name>Intersection_1_MovementState_2_MovementEvent_minEndTime</Name>
        <Xpath>/SPAT/intersections/IntersectionState[1]/states/MovementState[2]/state-time-speed/MovementEvent/timing/minEndTime</Xpath>
        <OutputBehavior>Number</OutputBehavior>
        <MaxLength></MaxLength>
        <Invalid>-1</Invalid>
    </Entry>
    <Entry>
        <Name>Intersection_1_MovementState_2_MovementEvent_likelyTime</Name>
        <Xpath>/SPAT/intersections/IntersectionState[1]/states/MovementState[2]/state-time-speed/MovementEvent/timing/likelyTime</Xpath>
        <OutputBehavior>Number</OutputBehavior>
        <MaxLength></MaxLength>
        <Invalid>-1</Invalid>
    </Entry>
    <Entry>
        <Name>Intersection_1_MovementState_2_MovementEvent_maxEndTime</Name>
        <Xpath>/SPAT/intersections/IntersectionState[1]/states/MovementState[2]/state-time-speed/MovementEvent/timing/maxEndTime</Xpath>
        <OutputBehavior>Number</OutputBehavior>
        <MaxLength></MaxLength>
        <Invalid>-1</Invalid>
    </Entry>
    <Entry>
        <Name>Intersection_1_MovementState_2_MovementEvent_confidence</Name>
        <Xpath>/SPAT/intersections/IntersectionState[1]/states/MovementState[2]/state-time-speed/MovementEvent/timing/confidence</Xpath>
        <OutputBehavior>Number</OutputBehavior>
        <MaxLength></MaxLength>
        <Invalid>-1</Invalid>
    </Entry>
    <Entry>
        <Name>Intersection_1_MovementState_2_MovementEvent_nextTime</Name>
        <Xpath>/SPAT/intersections/IntersectionState[1]/states/MovementState[2]/state-time-speed/MovementEvent/timing/nextTime</Xpath>
        <OutputBehavior>Number</OutputBehavior>
        <MaxLength></MaxLength>
        <Invalid>-1</Invalid>
    </Entry>
</ArrayOfEntry>
